apiVersion: apps/v1
kind: Deployment
metadata: 
  name: t4deploy  
spec:
  replicas: 1
  selector:
    matchLabels:
        env: dev
  template:
    metadata:
     name: t4pod
     labels:
       env: dev
    spec:
     containers:
      - name: t4con
        image: ishandsce/kubectl:latest
